# Symlink this file to ~/.config/starship.toml
# ln -s absolute/path/of/this/file ~/.config/starship.toml

# ========= config start ================
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"
# right_format = "$all" -> this is annoying when coppying commands
add_newline = true
command_timeout = 700

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[!](bold red)'
disabled = false

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[line_break]
disabled = true

[fill]
symbol = " "

[package]
disabled = true

[directory]
truncate_to_repo = false
style = "white dimmed"

[jobs]
symbol = "+ "
number_threshold = 1

[git_branch]
format = "[$symbol$branch]($style) "
style = "white"

[time]
disabled = true
style = "white"
format = "[$time]($style) "

[cmd_duration]
disabled = true
format = "[$duration]($style) "

[golang]
disabled = true

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[status]
disabled = false
format = "[$status]($style) "

[memory_usage]
disabled = false
threshold = 80
format = "[Mem$ram_pct Swp$swap_pct]($style) "
style = "bold dimmed white"
# ========= config end ================
