# Symlink this file to ~/.config/starship.toml
# ln -s absolute/path/of/this/file ~/.config/starship.toml

format = "$character"
right_format = "$all"
add_newline = false
command_timeout = 500

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[!](bold red)'

[fill]
symbol = " "

[package]
disabled = true

[directory]
truncate_to_repo = false
style = "white dimmed"

[git_branch]
format = "[$symbol$branch]($style) "
style = "white"

[time]
disabled = true
style = "white"
format = "[$time]($style) "

[cmd_duration]
disabled = true
format = "[$duration]($style) "

[golang]
disabled = true

[status]
disabled = false
format = "[$status]($style) "

[memory_usage]
disabled = false
threshold = -1
format = "${ram_pct} "
